### PR TITLE
Fix ugly fix using Handler to set toolbar's title

### PR DESCRIPTION
**Pull request by krossovochkin**
Removed ugly hack for setting toolbar's title.
:(
Just call setTItle method in onPostCreate

### CODE REVIEW

**Comment by dannyroa** [comment]
I know it can be done on onPostCreate. But it's still ugly to me.

The iosched app seems to be doing either onPostCreate or Handler.

**Comment by krossovochkin** [comment]
But at least with onPostCreate this is less code.
Anyway, this is the matter of taste, I think :)

**Comment by krossovochkin** [comment]
And in addition.
Yes, you are right, I found your variant in ioshed app (line 197):
https://github.com/google/iosched/blob/dfaf8b83ad1b3e7c8d1af0b08d59caf4223e0b95/android/src/main/java/com/google/samples/apps/iosched/ui/SessionDetailActivity.java

**Comment by dannyroa** [comment]
I have no idea why Google is doing both approaches in the ioSched app.

I guess I wanted the Handler to show the odd behavior of the toolbar.

I bet this is going to get fixed soon.

**Comment by krossovochkin** [comment]
Will hope for it :)

**Comment by dannyroa** [comment]
Heard back from Google. Looks like we should be referencing the ActionBar instead of Toolbar.

I'll update the code when I get home.

**Comment by krossovochkin** [comment]
Hmm, could you give me reference for this update about using action bar instead of toolbar? I couldn't find it by myself...

**Comment by dannyroa** [comment]
See this commit: https://github.com/greenhalolabs/lollipopsamples/commit/e4ac09fd6e6a71aa1e4851ccf0c31f592ce6537b

**Comment by krossovochkin** [comment]
Yes, nice solution :+1:

**Pull request closed without merging**
